spring:
  application:
    name: lifestyle-app
  datasource:
    url: jdbc:h2:file:./data/lsdb;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: admin
    password: admin
  jpa:
    hibernate:
      ddl-auto: update
  sql:
    init:
      platform: h2

logging:
  level:
    org.springframework.web.filter.CommonsRequestLoggingFilter: DEBUG